/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrilhasRouteImport } from './routes/trilhas'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NovoTestamentoRouteImport } from './routes/novo-testamento'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as JornadaRouteImport } from './routes/jornada'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as AntigoTestamentoRouteImport } from './routes/antigo-testamento'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaSlugRouteImport } from './routes/biblioteca.$slug'
import { Route as BibliotecaGenesisJornada1RouteImport } from './routes/biblioteca.genesis.jornada-1'
import { Route as BibliotecaGenesisJornada1StorySlugRouteImport } from './routes/biblioteca.genesis.jornada-1.$storySlug'

const TrilhasRoute = TrilhasRouteImport.update({
  id: '/trilhas',
  path: '/trilhas',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoTestamentoRoute = NovoTestamentoRouteImport.update({
  id: '/novo-testamento',
  path: '/novo-testamento',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaRoute = JornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const AntigoTestamentoRoute = AntigoTestamentoRouteImport.update({
  id: '/antigo-testamento',
  path: '/antigo-testamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaSlugRoute = BibliotecaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BibliotecaRoute,
} as any)
const BibliotecaGenesisJornada1Route =
  BibliotecaGenesisJornada1RouteImport.update({
    id: '/genesis/jornada-1',
    path: '/genesis/jornada-1',
    getParentRoute: () => BibliotecaRoute,
  } as any)
const BibliotecaGenesisJornada1StorySlugRoute =
  BibliotecaGenesisJornada1StorySlugRouteImport.update({
    id: '/$storySlug',
    path: '/$storySlug',
    getParentRoute: () => BibliotecaGenesisJornada1Route,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/antigo-testamento': typeof AntigoTestamentoRoute
  '/atividades': typeof AtividadesRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/design-system': typeof DesignSystemRoute
  '/favoritos': typeof FavoritosRoute
  '/jornada': typeof JornadaRoute
  '/materiais': typeof MateriaisRoute
  '/novo-testamento': typeof NovoTestamentoRoute
  '/perfil': typeof PerfilRoute
  '/quizzes': typeof QuizzesRoute
  '/trilhas': typeof TrilhasRoute
  '/biblioteca/$slug': typeof BibliotecaSlugRoute
  '/biblioteca/genesis/jornada-1': typeof BibliotecaGenesisJornada1RouteWithChildren
  '/biblioteca/genesis/jornada-1/$storySlug': typeof BibliotecaGenesisJornada1StorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/antigo-testamento': typeof AntigoTestamentoRoute
  '/atividades': typeof AtividadesRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/design-system': typeof DesignSystemRoute
  '/favoritos': typeof FavoritosRoute
  '/jornada': typeof JornadaRoute
  '/materiais': typeof MateriaisRoute
  '/novo-testamento': typeof NovoTestamentoRoute
  '/perfil': typeof PerfilRoute
  '/quizzes': typeof QuizzesRoute
  '/trilhas': typeof TrilhasRoute
  '/biblioteca/$slug': typeof BibliotecaSlugRoute
  '/biblioteca/genesis/jornada-1': typeof BibliotecaGenesisJornada1RouteWithChildren
  '/biblioteca/genesis/jornada-1/$storySlug': typeof BibliotecaGenesisJornada1StorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/antigo-testamento': typeof AntigoTestamentoRoute
  '/atividades': typeof AtividadesRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/design-system': typeof DesignSystemRoute
  '/favoritos': typeof FavoritosRoute
  '/jornada': typeof JornadaRoute
  '/materiais': typeof MateriaisRoute
  '/novo-testamento': typeof NovoTestamentoRoute
  '/perfil': typeof PerfilRoute
  '/quizzes': typeof QuizzesRoute
  '/trilhas': typeof TrilhasRoute
  '/biblioteca/$slug': typeof BibliotecaSlugRoute
  '/biblioteca/genesis/jornada-1': typeof BibliotecaGenesisJornada1RouteWithChildren
  '/biblioteca/genesis/jornada-1/$storySlug': typeof BibliotecaGenesisJornada1StorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/antigo-testamento'
    | '/atividades'
    | '/biblioteca'
    | '/configuracoes'
    | '/design-system'
    | '/favoritos'
    | '/jornada'
    | '/materiais'
    | '/novo-testamento'
    | '/perfil'
    | '/quizzes'
    | '/trilhas'
    | '/biblioteca/$slug'
    | '/biblioteca/genesis/jornada-1'
    | '/biblioteca/genesis/jornada-1/$storySlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/antigo-testamento'
    | '/atividades'
    | '/biblioteca'
    | '/configuracoes'
    | '/design-system'
    | '/favoritos'
    | '/jornada'
    | '/materiais'
    | '/novo-testamento'
    | '/perfil'
    | '/quizzes'
    | '/trilhas'
    | '/biblioteca/$slug'
    | '/biblioteca/genesis/jornada-1'
    | '/biblioteca/genesis/jornada-1/$storySlug'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/antigo-testamento'
    | '/atividades'
    | '/biblioteca'
    | '/configuracoes'
    | '/design-system'
    | '/favoritos'
    | '/jornada'
    | '/materiais'
    | '/novo-testamento'
    | '/perfil'
    | '/quizzes'
    | '/trilhas'
    | '/biblioteca/$slug'
    | '/biblioteca/genesis/jornada-1'
    | '/biblioteca/genesis/jornada-1/$storySlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  AntigoTestamentoRoute: typeof AntigoTestamentoRoute
  AtividadesRoute: typeof AtividadesRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DesignSystemRoute: typeof DesignSystemRoute
  FavoritosRoute: typeof FavoritosRoute
  JornadaRoute: typeof JornadaRoute
  MateriaisRoute: typeof MateriaisRoute
  NovoTestamentoRoute: typeof NovoTestamentoRoute
  PerfilRoute: typeof PerfilRoute
  QuizzesRoute: typeof QuizzesRoute
  TrilhasRoute: typeof TrilhasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trilhas': {
      id: '/trilhas'
      path: '/trilhas'
      fullPath: '/trilhas'
      preLoaderRoute: typeof TrilhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-testamento': {
      id: '/novo-testamento'
      path: '/novo-testamento'
      fullPath: '/novo-testamento'
      preLoaderRoute: typeof NovoTestamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada': {
      id: '/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof JornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antigo-testamento': {
      id: '/antigo-testamento'
      path: '/antigo-testamento'
      fullPath: '/antigo-testamento'
      preLoaderRoute: typeof AntigoTestamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/$slug': {
      id: '/biblioteca/$slug'
      path: '/$slug'
      fullPath: '/biblioteca/$slug'
      preLoaderRoute: typeof BibliotecaSlugRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/genesis/jornada-1': {
      id: '/biblioteca/genesis/jornada-1'
      path: '/genesis/jornada-1'
      fullPath: '/biblioteca/genesis/jornada-1'
      preLoaderRoute: typeof BibliotecaGenesisJornada1RouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/genesis/jornada-1/$storySlug': {
      id: '/biblioteca/genesis/jornada-1/$storySlug'
      path: '/$storySlug'
      fullPath: '/biblioteca/genesis/jornada-1/$storySlug'
      preLoaderRoute: typeof BibliotecaGenesisJornada1StorySlugRouteImport
      parentRoute: typeof BibliotecaGenesisJornada1Route
    }
  }
}

interface BibliotecaGenesisJornada1RouteChildren {
  BibliotecaGenesisJornada1StorySlugRoute: typeof BibliotecaGenesisJornada1StorySlugRoute
}

const BibliotecaGenesisJornada1RouteChildren: BibliotecaGenesisJornada1RouteChildren =
  {
    BibliotecaGenesisJornada1StorySlugRoute:
      BibliotecaGenesisJornada1StorySlugRoute,
  }

const BibliotecaGenesisJornada1RouteWithChildren =
  BibliotecaGenesisJornada1Route._addFileChildren(
    BibliotecaGenesisJornada1RouteChildren,
  )

interface BibliotecaRouteChildren {
  BibliotecaSlugRoute: typeof BibliotecaSlugRoute
  BibliotecaGenesisJornada1Route: typeof BibliotecaGenesisJornada1RouteWithChildren
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaSlugRoute: BibliotecaSlugRoute,
  BibliotecaGenesisJornada1Route: BibliotecaGenesisJornada1RouteWithChildren,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  AntigoTestamentoRoute: AntigoTestamentoRoute,
  AtividadesRoute: AtividadesRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DesignSystemRoute: DesignSystemRoute,
  FavoritosRoute: FavoritosRoute,
  JornadaRoute: JornadaRoute,
  MateriaisRoute: MateriaisRoute,
  NovoTestamentoRoute: NovoTestamentoRoute,
  PerfilRoute: PerfilRoute,
  QuizzesRoute: QuizzesRoute,
  TrilhasRoute: TrilhasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
